[package]
name = "promanage"
version = "0.1.0"
description = "ProManage desktop app"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"

[build-dependencies]
tauri-build = { version = "2" }
